### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by romankh** [swagger-api/swaggerhub-maven-plugin#50]
Hi, 

as far as I have seen, currently the plugin does not support proxies (e.g. from Maven's settings.xml) ?
Is this planned somehow ?
Would you accept pull requests ?

**Comment by jmchen** [comment]
Created a pull request for this issue.
https://github.com/swagger-api/swaggerhub-maven-plugin/pull/57

**Comment by echen-uxp** [comment]
Is there anyone review and merge this PR?
