### ISSUE TITLE
Execution config is ignored

### ISSUE THREAD

**Issue by gerdzhikov** [swagger-api/swaggerhub-maven-plugin#6]
Hi,
I've just tried this plugin, but I think there is some problems on configuring the execution:
This is the configuration:

> <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swaggerhub-maven-plugin</artifactId>
                <version>1.0.2</version>
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>download</goal>
                        </goals>
                        <configuration>
                            <owner>gerdzhikov</owner>
                            <api>testApi</api>
                            <version>1.0.0</version>
                            <outputFile>target/petStoreAPI.json</outputFile>
                            <token>eyJ...</token>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

Runnig Maven with `mvn swaggerhub:download -X` fails with the following output:

> 
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          io.swagger:swaggerhub-maven-plugin:1.0.2:download (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: `<?xml version="1.0" encoding="UTF-8"?>`
`<configuration>`
`  <api>${download.api}</api>`
`  <format default-value="json">${download.format}</format>`
`  <host default-value="api.swaggerhub.com">${download.host}</host>`
`  <outputFile>${download.outputFile}</outputFile>`
`  <owner>${download.owner}</owner>`
`  <port default-value="443">${download.port}</port>`
`  <protocol default-value="https">${download.protocol}</protocol>`
`  <token>${download.token}</token>`
`  <version>${download.version}</version>`
`</configuration>`
[DEBUG] =======================================================================
...
[DEBUG] Configuring mojo 'io.swagger:swaggerhub-maven-plugin:1.0.2:download' with basic configurator -->
[DEBUG]   (f) format = json
[DEBUG]   (f) host = api.swaggerhub.com
[DEBUG]   (f) port = 443
[DEBUG]   (f) protocol = https
[DEBUG] -- end configuration --
...
[ERROR] Failed to execute goal io.swagger:swaggerhub-maven-plugin:1.0.2:download (default-cli) on project member-module: The parameters 'owner', 'outputFile', 'api', 'version' for goal io.swagger:swaggerhub-maven-plugin:1.0.2:download are missing or invalid -> [Help 1]

When the Maven variables: `download.api`, `download.owner`, `download.token`, `download.version` and `download.outputFile` are set in the `<properties>` section of the POM, than everything work exactley as expected.

Am I doing something wrong, or this is some bug?

**Comment by jsfrench** [comment]
Your configuration ties the execution of the `download` goal (and the associated configuration) to the `generate-resources` phase of the build lifecycle. When you run `mvn swaggerhub:download`, the `generate-resources` phase doesn't get executed, so there is no valid configuration. If you run `mvn generate-resources` (or any build phase that includes this phase), then your configuration will be picked and the `download` goal will run.

Alternatively you can set up a global configuration 
```xml
    <build>
        <plugins>
            <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swaggerhub-maven-plugin</artifactId>
                <version>1.0.2</version>
                <goals>
                    <goal>download</goal>
                </goals>
                <configuration>
                    <owner>gerdzhikov</owner>
                    <api>testApi</api>
                    <version>1.0.0</version>
                    <outputFile>target/petStoreAPI.json</outputFile>
                    <token>eyJ...</token>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
then you can run `mvn swaggerhub:download`. 

The example usage in the README is probably the cause of this confusion, i'll look at updating it to make it clearer.

**Comment by gerdzhikov** [comment]
Thank you man, it works perfectly as expected! 
Regards,
A.
